import type { Project } from '@/types/project'

export const projects: Project[] = [
  {
    id: 1,
    title: 'Sistem Informasi Desa Digital',
    slug: 'sistem-informasi-desa-digital',
    description:
      'Platform pelayanan publik terpadu untuk desa, mencakup administrasi kependudukan, surat menyurat online, dan transparansi anggaran desa.',
    content: null,
    status: 'completed',
    client_id: null,
    service_id: 1,
    project_url: 'https://desadigital.example.com',
    repository_url: null,
    started_at: '2025-01-10',
    completed_at: '2025-03-15',
    price: null,
    payment_status: 'paid',
    is_featured: true,
    order: 1,
    images: [
      {
        id: 1,
        project_id: 1,
        image_path:
          'https://images.unsplash.com/photo-1540350394557-8d14678e7f91?q=80&w=1000&auto=format&fit=crop',
        title: 'Dashboard Admin',
        order: 1,
        is_thumbnail: true,
      },
      {
        id: 101,
        project_id: 1,
        image_path: 'https://picsum.photos/800/600?random=101',
        title: 'Fitur Surat Online',
        order: 2,
        is_thumbnail: false,
      },
      {
        id: 102,
        project_id: 1,
        image_path: 'https://picsum.photos/800/600?random=102',
        title: 'Manajemen Penduduk',
        order: 3,
        is_thumbnail: false,
      },
      {
        id: 103,
        project_id: 1,
        image_path: 'https://picsum.photos/800/600?random=103',
        title: 'Laporan Anggaran',
        order: 4,
        is_thumbnail: false,
      },
    ],
    technologies: [
      { id: 1, name: 'Vue.js', icon: 'vue', slug: 'vue-js', category: 'frontend' },
      { id: 2, name: 'Laravel', icon: 'laravel', slug: 'laravel', category: 'backend' },
      { id: 3, name: 'MySQL', icon: 'mysql', slug: 'mysql', category: 'database' },
      { id: 4, name: 'Tailwind', icon: 'tailwind', slug: 'tailwind', category: 'frontend' },
    ],
  },
  {
    id: 2,
    title: 'E-Commerce UMKM Konawe',
    slug: 'ecommerce-umkm-konawe',
    description:
      'Marketplace lokal untuk memberdayakan UMKM di Konawe, memungkinkan transaksi jual beli produk lokal dengan integrasi pembayaran digital.',
    content: null,
    status: 'completed',
    client_id: null,
    service_id: 2,
    project_url: 'https://umkmkonawe.example.com',
    repository_url: null,
    started_at: '2025-04-01',
    completed_at: '2025-06-20',
    price: null,
    payment_status: 'paid',
    is_featured: true,
    order: 2,
    images: [
      {
        id: 2,
        project_id: 2,
        image_path:
          'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?q=80&w=1000&auto=format&fit=crop',
        title: 'Halaman Produk',
        order: 1,
        is_thumbnail: true,
      },
      {
        id: 201,
        project_id: 2,
        image_path: 'https://picsum.photos/800/600?random=201',
        title: 'Keranjang Belanja',
        order: 2,
        is_thumbnail: false,
      },
      {
        id: 202,
        project_id: 2,
        image_path: 'https://picsum.photos/800/600?random=202',
        title: 'Checkout Process',
        order: 3,
        is_thumbnail: false,
      },
      {
        id: 203,
        project_id: 2,
        image_path: 'https://picsum.photos/800/600?random=203',
        title: 'Dashboard Penjual',
        order: 4,
        is_thumbnail: false,
      },
    ],
    technologies: [
      { id: 5, name: 'React', icon: 'react', slug: 'react', category: 'frontend' },
      { id: 6, name: 'Node.js', icon: 'nodejs', slug: 'node-js', category: 'backend' },
      { id: 7, name: 'PostgreSQL', icon: 'postgresql', slug: 'postgresql', category: 'database' },
    ],
  },
  {
    id: 3,
    title: 'Company Profile Tambang Nikel',
    slug: 'compro-tambang-nikel',
    description:
      'Website profil perusahaan tambang dengan desain korporat modern, menampilkan portofolio operasional, laporan keberlanjutan, dan karir.',
    content: null,
    status: 'completed',
    client_id: null,
    service_id: 1,
    project_url: 'https://miningcorp.example.com',
    repository_url: null,
    started_at: '2025-07-15',
    completed_at: '2025-08-30',
    price: null,
    payment_status: 'paid',
    is_featured: false,
    order: 3,
    images: [
      {
        id: 3,
        project_id: 3,
        image_path:
          'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
        title: 'Homepage',
        order: 1,
        is_thumbnail: true,
      },
      {
        id: 301,
        project_id: 3,
        image_path: 'https://picsum.photos/800/600?random=301',
        title: 'Tentang Kami',
        order: 2,
        is_thumbnail: false,
      },
      {
        id: 302,
        project_id: 3,
        image_path: 'https://picsum.photos/800/600?random=302',
        title: 'Operasional',
        order: 3,
        is_thumbnail: false,
      },
      {
        id: 303,
        project_id: 3,
        image_path: 'https://picsum.photos/800/600?random=303',
        title: 'Karir',
        order: 4,
        is_thumbnail: false,
      },
    ],
    technologies: [
      { id: 8, name: 'Next.js', icon: 'nextjs', slug: 'next-js', category: 'frontend' },
      { id: 9, name: 'Framer Motion', icon: 'framer', slug: 'framer-motion', category: 'frontend' },
    ],
  },
  {
    id: 4,
    title: 'Aplikasi Absensi Geolocation',
    slug: 'absensi-geolocation',
    description:
      'Sistem absensi berbasis mobile app untuk pegawai negeri, menggunakan validasi lokasi GPS dan pengenalan wajah.',
    content: null,
    status: 'completed',
    client_id: null,
    service_id: 3,
    project_url: null,
    repository_url: null,
    started_at: '2025-02-10',
    completed_at: '2025-05-01',
    price: null,
    payment_status: 'paid',
    is_featured: false,
    order: 4,
    images: [
      {
        id: 4,
        project_id: 4,
        image_path:
          'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1000&auto=format&fit=crop',
        title: 'Mobile App Interface',
        order: 1,
        is_thumbnail: true,
      },
      {
        id: 401,
        project_id: 4,
        image_path: 'https://picsum.photos/800/600?random=401',
        title: 'Login Screen',
        order: 2,
        is_thumbnail: false,
      },
      {
        id: 402,
        project_id: 4,
        image_path: 'https://picsum.photos/800/600?random=402',
        title: 'Scan Wajah',
        order: 3,
        is_thumbnail: false,
      },
      {
        id: 403,
        project_id: 4,
        image_path: 'https://picsum.photos/800/600?random=403',
        title: 'History Absensi',
        order: 4,
        is_thumbnail: false,
      },
    ],
    technologies: [
      { id: 10, name: 'Flutter', icon: 'flutter', slug: 'flutter', category: 'mobile' },
      { id: 11, name: 'Firebase', icon: 'firebase', slug: 'firebase', category: 'backend' },
    ],
  },
  {
    id: 5,
    title: 'Sistem Manajemen Aset Daerah',
    slug: 'sistem-manajemen-aset',
    description:
      'Aplikasi web untuk pencatatan dan pelacakan aset daerah, dilengkapi dengan fitur audit trail dan pelaporan penyusutan aset otomatis.',
    content: null,
    status: 'planning', // Should be filtered out
    client_id: null,
    service_id: 1,
    project_url: null,
    repository_url: null,
    started_at: '2025-09-01',
    completed_at: null,
    price: null,
    payment_status: 'unpaid',
    is_featured: false,
    order: 5,
    images: [],
    technologies: [],
  },
]
